dist: bionic
language: java

jobs:
  include:
    - stage: compile
      script: mvn package
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: target/*.jar
        cleanup: false
        skip_cleanup: true
        on:
          tags: true