main: be.renaud11232.slappy.SlappyPlugin
name: Slappy
version: "1.0"
description: Allows to slap naught players
author: Renaud11232

commands:
  slap:
    description: Slaps a naughty player
    usage: /<command> <player> [slapness]
    permission: slappy.slap

permissions:
  slappy.slap:
    description: Allows a user to slap another player
    default: op