main: be.renaud11232.slappy.SlappyPlugin
name: Slappy
version: '${project.version}'
description: Allows to slap naughty players
author: Renaud11232
api-version: 1.13

commands:
  slap:
    description: Slaps a naughty player
    usage: /<command> <player> [slapness]
    permission: slappy.slap
  punch:
    description: Punches a naughty player
    usage: /<command> <player> <damage> [slapness]
    permission: slappy.punch

permissions:
  slappy.slap:
    description: Allows a user to slap another player
    default: op
  slappy.punch:
    description: Allows a user to punch another player
    default: op
