name: Build
on:
  - release
  - push
jobs:
  build:
    name: Build plugin JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn package
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          path: target/slappy*.jar
  upload_release:
    name: Upload built jar to release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download build results
        uses: actions/download-artifact@v3
        with:
          path: target
      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/*.jar
          asset_name: slappy.jar

